### ISSUE TITLE
Grafana won't generate a graph

### ISSUE THREAD

**Issue by francizs** [hawkular/hawkular-grafana-datasource#55]
No graphs are being generated by Grafana although a correct Data Source has been added. I have tried doing a curl with multiple different tags to hawkular-metrics and I get a response with data. Some examples:

`curl -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -H "Hawkular-Tenant: ci" -X GET 'https://hawkular-metrics.env.xxxxxxx/hawkular/metrics/counters/data?stacked=true&tags=descriptor_name:cpu%2Fusage,type:pod_container,labels:%5E%28%3F%3D.%2A%5Cbapplication%3Axxxx-xxxxxx-xxxxximpl%5Cb%29%28%3F%3D.%2A%5Cbdeployment%3Axxxx-xxxxxx-xxxxximpl-6%5Cb%29%28%3F%3D.%2A%5Cbdeploymentconfig%3Axxxx-xxxxxx-xxxxximpl%5Cb%29.%2A%24&bucketDuration=60000ms&start=1485884985375' --insecure
`
![capture2](https://cloud.githubusercontent.com/assets/5638446/22485290/c52918f2-e80d-11e6-81da-b590891857ed.PNG)

`curl -H "Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" -H "Hawkular-Tenant: ci" -X GET 'https://hawkular-metrics.env.xxxxxxx/hawkular/metrics/counters/data?stacked=true&tags=collector:hawkular_openshift_agent,type:pod,labels:%5E%28%3F%3D.%2A%5Cbapplication%3Axxxx-xxxxxx-xxxxximpl%5Cb%29%28%3F%3D.%2A%5Cbdeployment%3Axxxx-xxxxxx-xxxxximpl-6%5Cb%29%28%3F%3D.%2A%5Cbdeploymentconfig%3Axxxx-xxxxxx-xxxxximpl%5Cb%29.%2A%24&bucketDuration=60000ms&start=1485884985375' --insecure`

![capture3](https://cloud.githubusercontent.com/assets/5638446/22485393/39309766-e80e-11e6-8493-47231e316060.PNG)

So this data should appear in Grafana but it doesn't. Grafana even automatically suggests which metrics to draw:

![capture4](https://cloud.githubusercontent.com/assets/5638446/22485592/e947c160-e80e-11e6-8451-7e88a45b289b.PNG)

but when I choose nothing happens.

**Comment by jotak** [comment]
Hi @francizs 

Can you check your version of both hawkular-metrics and the hawkular-grafana-datasource? Based on your screenshots, it seems a bit old (no search by tags capability) and, knowing that some old versions were not able to speak with openshift pods, I fear it's the problem here.

Note, in order to know your version of hawkular-metrics you can check the endpoint (GET) `/hawkular/metrics/status` with your authorization token in headers.
The version of the grafana plugin is given in the Plugins page of Grafana under datasources.

**Comment by francizs** [comment]
@jotak hello agian! 

{"MetricsService":"STARTED","Implementation-Version":"0.18.4.Final-redhat-1" and 
Grafana v3.1.1 (commit: a4d2708).

**You can either search by metric id or by tag, assuming your version of hawkular-metrics is at least 0.20.0. Prior versions only allow searching by id. I saw that but assumed it shouldn't give any problems to get themetrics.** 

So this version 0.18.4.Final-redhat-1 must be too old and is not able to receive data from pods? Will try to update the version but could I ask for a suggested version for production? I will try latest for now but it would be great to know the most stable one, thanks!

**Comment by jotak** [comment]
Actually, 0.18.xx should work with openshift pods. I would personally recommend a newer version, especially in the context of openshift + grafana because querying by tags offers a much more flexible way to build dashboards (I wrote [a blog post about it](http://www.hawkular.org/blog/2016/10/24/hawkular-metrics-openshift-and-grafana.html)).

I'm not especially aware of a version of Hawkular that would be "better for production". 0.19.x added some performance improvements, 0.20.x added a compression algorithm, and til 0.23.x there's been again performance and compression enhancements so I'd say it's all benefits for a production environment. But I am not the best placed to answer your question here, so I'll check that with my colleagues.

Even if you want to continue with 0.18, there's a couple of things you can further check to sort out this issue:

- Can you check in the hawkular datasource configuration (in Grafana) if you're in "proxy" mode and not "direct" mode
- Can you open the javascript console of your browser, and see if there's any error? You can also track here the requests to hawkular-metrics and try to see if there's something weird.
- Does restarting grafana-server fix the problem?

**Comment by francizs** [comment]
@jotak First of all I set the latest version and I can see the graph now! It seems 0.18 still has some issues with connecting to pods.

Regarding 0.18 version, I have tried 2 of the points you suggested and
1) I am/was using **direct** in Grafana
2) Haven't tried inspecting the webpage code
2) Restarting was done multiple times

Thanks for helping out!

**Comment by jotak** [comment]
You're welcome. So, if you're fine with the latest version, I'll close the issue. But if you want to stick to 0.18 then you would have to use the proxy mode in Grafana, not direct.
You can let me know / reopen if it's not ok.
