### ISSUE TITLE
query tags with grafana variables

### ISSUE THREAD

**Issue by ljuaneda** [hawkular/hawkular-grafana-datasource#60]
templating is a great feature in grafana

it would be nice to be able to nest variable

$nodename with query=tags/nodename:.*
$metric with query=tags/nodename:**$nodename**,descriptor_name:.*

**Comment by jotak** [comment]
We can implement nested variables, however I am not sure about this use case because here, with your query `tags/nodename:$nodename,descriptor_name:.*` you would get tags for both `nodename` and `descriptor_name`, mixed together. I guess this is not what you want, you want only the descriptor names here.

In other words, we must find a way to distinguish in query the tags that we want to be returned from the ones used for refining the query. Some kind of query language: SELECT descriptor_name WHERE nodename=$nodename. That brings the feature request to another level :)

**Comment by jotak** [comment]
I've added support for nested variable (PR #61 to be merged) , however as said above I doubt it will be enough for your use case. Next step could be a better query language, that we could put in relation with https://github.com/hawkular/hawkular-grafana-datasource/issues/52

**Comment by ljuaneda** [comment]
thanks, indeed it could be better with the query language.

**Comment by jotak** [comment]
The tags query language has been released since 1.0.8
