### ISSUE TITLE
Hawkular Tenants as query variable

### ISSUE THREAD

**Issue by ljuaneda** [hawkular/hawkular-grafana-datasource#62]
With Openshift-Metrics, the hawkular tenant is hardcoded to the pod namespace.
When you have hundred of namespaces, it's not conveniant to declare that much datasources in grafana.

Could it be possible to make tenants a variable ?
Maybe, it's even possible to populate this automatically calling API REST point /tenants

**Comment by jotak** [comment]
That's interesting. We could add a checkbox in the datasource configuration, to enable per-query tenant. When enabled, a new field appears for each query to ask for a tenant.

However, having an automatically populated list of tenants seems problematic to me, because the /tenants endpoint is admin-protected (maybe not in the version of Hawkular you are using, it's been protected since 0.20.0). An admin token is necessary to call it.

But still, it will be possible to put all used tenants in a variable of type Custom (= coma-separated list) to create dynamic dashboard across OS projects.

Seems like a plan?
(PS I couldn't give any ETA for that)

**Comment by tsegismont** [comment]
2017-03-03 14:46 GMT+01:00 Joel Takvorian <notifications@github.com>:

> That's interesting. We could add a checkbox in the datasource
> configuration, to enable per-query tenant. When enabled, a new field
> appears for each query to ask for a tenant.
>
How would authentication work? Isn't the password tenant related?

**Comment by jotak** [comment]
As far as I know, in openshift you can create a service account that has rights on several projects ; so I guess you can set its token and use it for several tenants. Though I never tested.

**Comment by ljuaneda** [comment]
That's right, openshift relies on service accounts, to get the tenants list
you actually don't have to specify a real tenant in hawkular :

[root@siy05ez1:~]# curl -k -H "Hawkular-Tenant: *FAKE*" -H "Authorization:
Bearer $(oc sa get-token -n management-infra management-admin)" "
https://metrics.osev3-qt9-infra.hpmetier.sf.intra.laposte.fr/hawkular/metrics/tenants"
-X GET -s  | jq .[].id
"default"
"tfon-qt9stome1"
"stom-apps-build"
"storage-project"
"logging"
"openshift-infra"
"asse-qt9stome1"
"_system"
"metrics-grafana"
"asse-qt9stome2"


Le lun. 6 mars 2017 à 11:48, Joel Takvorian <notifications@github.com> a
écrit :

**Comment by gildean** [comment]
I can confirm that you can create a service account that has rights to multiple projects. I'd very much appreciate this feature as well.

**Comment by jotak** [comment]
Done

**Comment by kalote** [comment]
Hello,

Where is the doc on how to use it? how to set the variant per query => ok, it's in the datasource config, but how to set up the tenant as a variable in the dashboard (and how to use it when making a new panel)
Thanks

**Comment by jotak** [comment]
@kalote yes, sorry, you're right that some documentation is missing. Just created an issue about that: https://github.com/hawkular/hawkular-grafana-datasource/issues/104
Thanks for reporting.
