### ISSUE TITLE
Alerting shows error

### ISSUE THREAD

**Issue by valsaraj** [hawkular/hawkular-grafana-datasource#78]
Error while setting alert in Grafana:

> tsdb.HandleRequest() error Could not find executor for data source type: hawkular-datasource

**Comment by jotak** [comment]
Alerting is not available with the hawkular datasource (or any other third-party datasource since there's no public API for that), so you cannot use alerts from within Grafana.

However hawkular has its own alerting engine that you could use instead, though it's not visible from grafana dashboards: example here http://www.hawkular.org/hawkular-services/docs/quickstart-guide/#_step_3_add_alerting
