### ISSUE TITLE
Dashboard for all tenants with Tenant per query

### ISSUE THREAD

**Issue by sshingarapu** [hawkular/hawkular-grafana-datasource#96]
Hi,

We have installed grafana with version 4.6.0. Installed hawkular-datasource plugin with version 1.1.1. 

Created one datasource for all tenants. Now we would like to build a dashboard for all the existing tenants(projects) by using regex or some other way in tenant field. We have more than 100 projects in openshift and it is very difficult to give each tenant name in tenant filed. 

Basically we are looking for a way if we can get all tenant names in a variable or if we can use regex in tenant field to get all tenants so that in one row we can configure dashboard for all tenants instead of having one row for each tenant.

Appreciate your help.

**Comment by jotak** [comment]
The problem is that there is no way to get the list of hawkular tenants from Grafana. The Hawkular API has a `/tenant` endpoint, but it is admin-protected and should not be used from the grafana plugin.

Maybe there's a possibility to do something using the Kubernetes and Grafana HTTP APIs: from the former, getting the list of namespaces (ie. Hawkular tenants) https://kubernetes.io/docs/api-reference/v1.8/#list-459
And from the latter, getting and updating dashboards, injecting in the meantime the list of tenants in the desired variable values: http://docs.grafana.org/http_api/dashboard/

Sorry to not have something better.

**Comment by sshingarapu** [comment]
Thanks Jotak. Sorry for the delay in response. We will try the above workaround and get back to you for any issues.
